batch_size: 32
channels: 16
checkpoints_path: ./checkpoints/flol-plus-run-vgg-lr_0.0004-channels_16-patience_32-lambda_0.1-seed_42_3cbeb74b
data_root: data
eta_min: 1.0e-06
grad_clip: 0.1
heldout_samples: 50
l1_weight: 1
lambda_lpips: 0.1
lr: 0.0004
min_delta: 0.0005
num_epochs: 128
num_fie_blocks: 3
num_fre_blocks: 4
num_workers: 16
patience: 32
run_name: flol-plus-run-vgg
scheduler_step: true
seed: 42
tensorboard_log_dir: ./runs/flol-plus-run-vgg-lr_0.0004-channels_16-patience_32-lambda_0.1-seed_42_3cbeb74b
